# Generated by Django 5.2.8 on 2026-07-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin', 'Administrateur'), ('manager', 'Manager'), ('employee', 'Employé'), ('client', 'Client')], default='employee', max_length=20),
        ),
    ]
