# Utiliser l'image Node.js officielle
FROM node:18-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY frontend/package.json frontend/package-lock.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code du frontend
COPY frontend/ .

# Construire l'application React
RUN npm run build

# Exposer le port 3000
EXPOSE 3000

# Commande pour démarrer le serveur de développement
CMD ["npm", "start"]