# Generated by Django 5.2.8 on 2026-08-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(default='Sénégal', max_length=100, verbose_name='Pays'),
        ),
    ]
