# Generated by Django 5.2.8 on 2026-07-22 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code compte')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du compte')),
                ('type', models.CharField(choices=[('asset', 'Actif'), ('liability', 'Passif'), ('equity', 'Capitaux propres'), ('income', 'Produits'), ('expense', 'Charges')], max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='companies.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.chartofaccount', verbose_name='Compte parent')),
            ],
            options={
                'verbose_name': 'Plan comptable',
                'verbose_name_plural': 'Plans comptables',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_type', models.CharField(choices=[('general', 'Journal général'), ('sales', 'Journal des ventes'), ('purchases', 'Journal des achats'), ('cash', 'Journal de caisse'), ('bank', 'Journal de banque')], default='general', max_length=20)),
                ('entry_number', models.CharField(max_length=50, verbose_name="Numéro d'écriture")),
                ('entry_date', models.DateField(verbose_name="Date d'écriture")),
                ('description', models.TextField(verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('is_balanced', models.BooleanField(default=False, verbose_name='Équilibrée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'ordering': ['-entry_date', '-entry_number'],
                'unique_together': {('company', 'entry_number')},
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_credit', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit')], max_length=10, verbose_name='Débit/Crédit')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='accounting.chartofaccount')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
            },
        ),
    ]
